server:
    port: 10004
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.67:10001/eureka
    fetch-registry: true
    register-with-eureka: true

spring:
  application:
    name: shop-order
  data:
    mongodb:
      authentication-database: admin
      database: mall
      host: 192.168.1.133
      port: 27017
      username: admin
      password: pwd



